---
- name: tomcat install playbook
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Java installation
      ansible.builtin.yum:
        name:  java-1.8.0-openjdk-devel
        state: present
    - name: Ensure group "tomcat" exists
      ansible.builtin.group:
        name: tomcat
        state: present
        system: true